# Generated by Django 5.0.4 on 2026-04-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('password_change', 'Password Change')], max_length=40)),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose'], name='accounts_em_email_fa28db_idx'), models.Index(fields=['expires_at'], name='accounts_em_expires_b9f6f7_idx'), models.Index(fields=['verified'], name='accounts_em_verified_394f28_idx')],
            },
        ),
    ]
