# Generated by Django 5.0.4 on 2026-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('job', 'Job'), ('exam', 'Exam')], max_length=30)),
                ('level', models.CharField(choices=[('10', 'Class 10'), ('12', 'Class 12'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(max_length=1000)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'link')},
            },
        ),
    ]
