# Generated by Django 5.0.4 on 2026-04-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.CharField(blank=True, default='', max_length=20)),
                ('interest_signature', models.TextField(blank=True, default='')),
                ('skill_signature', models.TextField(blank=True, default='')),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('total_available', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='alerts_modu_user_id_815dd8_idx'), models.Index(fields=['user_level'], name='alerts_modu_user_le_60e2c4_idx')],
            },
        ),
    ]
