# Generated by Django 5.0.4 on 2026-03-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('skill', 'Skill'), ('interest', 'Interest')], max_length=10),
        ),
    ]
