# Generated by Django 5.0.4 on 2026-03-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0003_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='profile_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
