# Generated by Django 5.0.4 on 2026-03-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
